/*MENU*/
export const CHANGE_MENU = 'CHANGE_MENU';

/*CATEGORIES*/
export const LIST_CATEGORIES = 'LIST_CATEGORIES';

/*POSTS*/
export const LIST_POSTS = 'LIST_POSTS';
export const LIST_POSTS_BY_CATEGORY = 'LIST_POSTS_BY_CATEGORY';
export const CREATE_POST = 'CREATE_POST';
export const GET_POST_BY_ID = 'GET_POST_BY_ID';
export const DELETE_POST = 'DELETE_POST';
export const VOTE_POST = 'VOTE_POST';
export const SORT_POST = 'SORT_POST';
export const EDIT_POST = 'EDIT_POST';

/*COMMENTS*/
export const LIST_COMMENTS_BY_POST = 'LIST_COMMENTS_BY_POST';
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const GET_COMMENT_BY_ID = 'GET_COMMENT_BY_ID';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const SHOW_FORM_EDIT_COMMENT = 'SHOW_FORM_EDIT_COMMENT';
export const SHOW_FORM_ADD_COMMENT = 'SHOW_FORM_ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const VOTE_COMMENT = 'VOTE_COMMENT';

